import initSeo from "remix-seo";

import imgHref from "~/media/phuket-pool.jpg";

export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
  // Pass any SEO defaults for your site here.
  // If individual routes do not provide their own meta and link tags,
  // the tags generated by the defaults will be used.
  title: "Jacob Thoughts",
  titleTemplate: "%s | Jacob Thoughts",
  description: "Come read my ramblings.",
  openGraph: {
    images: [
      {
        url: `https://jacobeby.com${imgHref}`,
        alt: "Jacob Ebey",
      },
    ],
  },
  twitter: {
    image: {
      url: `https://jacobeby.com${imgHref}`,
      alt: "Jacob Ebey",
    },
  },
});
